server {
    listen 80; # Ou a porta que seu docker-compose expõe para o frontend
    server_name localhost;
    root /usr/share/nginx/html;
    index index.html;

    location / {
        # A MÁGICA: Tenta achar o arquivo. Se não achar, manda pro index.html (React Router)
        try_files $uri $uri/ /index.html;
    }

    # Opcional: Se quiser que o Nginx faça proxy para o backend em vez do frontend chamar direto
    # location /api/ {
    #     proxy_pass http://backend:8080/api/;
    # }
}