services:
  db:
    image: mysql:8.0
    container_name: ${DB_DATABASE}
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    ports:
      - "${DB_PORT}:${DB_PORT}"
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - qa-prova_net
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: backend_qa_prova
    restart: always
    ports:
      - "${BACKEND_PORT}:${BACKEND_PORT}"
    environment:
      - CORS_ALLOWED_ORIGINS=http://localhost:3000,http://localhost:5173,http://localhost,http://127.0.0.1:3000
      - SPRING_DATASOURCE_URL=${DB_URL}
      - SPRING_DATASOURCE_USERNAME=${DB_USER}
      - SPRING_DATASOURCE_PASSWORD=${DB_PASSWORD}
      # - SPRING_PROFILES_ACTIVE=${SPRING_PROFILES_ACTIVE}
    depends_on:
      db:
        condition: service_healthy
    networks:
      - qa-prova_net

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: frontend_qa-prova
    restart: always
    ports:
      - "${FRONTEND_PORT}:${FRONTEND_DOCKER_PORT}"
    depends_on:
      - backend
    networks:
      - qa-prova_net

networks:
  qa-prova_net:
    driver: bridge

volumes:
  db_data:
