ALTER TABLE funcionarios
    ADD COLUMN created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    ADD COLUMN updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    ADD COLUMN created_by VARCHAR(255) DEFAULT 'sistema',
    ADD COLUMN updated_by VARCHAR(255) DEFAULT 'sistema';

ALTER TABLE cargos
    ADD COLUMN created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    ADD COLUMN updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    ADD COLUMN created_by VARCHAR(255) DEFAULT 'sistema',
    ADD COLUMN updated_by VARCHAR(255) DEFAULT 'sistema';

ALTER TABLE departamentos
    ADD COLUMN created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    ADD COLUMN updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    ADD COLUMN created_by VARCHAR(255) DEFAULT 'sistema',
    ADD COLUMN updated_by VARCHAR(255) DEFAULT 'sistema';

ALTER TABLE vinculos
    ADD COLUMN created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    ADD COLUMN updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    ADD COLUMN created_by VARCHAR(255) DEFAULT 'sistema',
    ADD COLUMN updated_by VARCHAR(255) DEFAULT 'sistema';
